apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .ServiceName }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: kubernetesproject.test
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .ServiceName }}
              servicePort: 80